import { library } from '@fortawesome/fontawesome-svg-core'
// import { fab } from '@fortawesome/free-brands-svg-icons'
import {
    faCheckSquare,
    faCoffee,
    faFileAlt,
    faKey,
    faSun,
    faSearch,
    faPrint,
    faPuzzlePiece,
    faPencil,
    faExplosion,
    faGamepad,
    faLink,
    faHome,
    faFilm,
    faIcons,
    faMessage,
    faTrash,
    faEllipsisVertical,
    faGlasses,
    faDiagramProject,
} from '@fortawesome/free-solid-svg-icons'

library.add(
    // fab,
    faCheckSquare,
    faCoffee,
    faFileAlt,
    faKey,
    faSun,
    faSearch,
    faPrint,
    faPuzzlePiece,
    faPencil,
    faExplosion,
    faGamepad,
    faLink,
    faHome,
    faFilm,
    faIcons,
    faMessage,
    faTrash,
    faEllipsisVertical,
    faGlasses,
    faDiagramProject,
)
